/**
 * Blackcoffer
 * Server of Blackcoffer Assignment
 *
 * OpenAPI spec version: 2.0.0
 * Contact: rogerthatvksingh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DataInner } from './dataInner';

export interface Data extends Array<DataInner> { 
}