/**
 * Blackcoffer Assignment
 * Backend server defining RESTful APIs of Blackcoffer Frontend
 *
 * OpenAPI spec version: 2.0.0
 * Contact: rogerthatvksingh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Filters { 
    end_year?: Array<number>;
    topic?: Array<string>;
    sector?: Array<string>;
    region?: Array<string>;
    pestle?: Array<string>;
    source?: Array<string>;
    country?: Array<string>;
}