/**
 * Blackcoffer Assignment
 * Backend server defining RESTful APIs of Blackcoffer Frontend
 *
 * OpenAPI spec version: 2.0.0
 * Contact: rogerthatvksingh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PieChartData { 
    /**
     * The name of the category or segment (e.g., \"World\", \"Northern America\")
     */
    name?: string;
    /**
     * The numerical value or size of the category or segment
     */
    value?: number;
    /**
     * Additional properties associated with the category or segment
     */
    extra?: any;
}