/**
 * Blackcoffer Assignment
 * Backend server defining RESTful APIs of Blackcoffer Frontend
 *
 * OpenAPI spec version: 2.0.0
 * Contact: rogerthatvksingh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StackedSeriesData } from './stackedSeriesData';

export interface StackedBarChartData { 
    /**
     * The name of the country
     */
    name?: string;
    series?: Array<StackedSeriesData>;
}