/**
 * Blackcoffer Assignment
 * Backend server defining RESTful APIs of Blackcoffer Frontend
 *
 * OpenAPI spec version: 2.0.0
 * Contact: rogerthatvksingh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VerticalBarChartData { 
    /**
     * The name or label of the category or bar (e.g., \"Oil\", \"Gas\")
     */
    name?: string;
    /**
     * The numerical value or height of the bar
     */
    value?: number;
}